name: Android CI One

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build ${{matrix.arch}} .apk
      run: |
        chmod +x gradlew
          ./gradlew assemblerelease -Darch=${{matrix.arch}}
    - name: capture build artifacts
      if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs/
